services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
